#!/usr/bin/env python

import sys

from rqt_contrail_commander.commander import Commander
from rqt_gui.main import Main

plugin = 'rqt_contrail_commander'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
